name: Generate Pac-Man Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # every Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Pac-Man generator
        run: npm install -g github-contribution-grid-snake

      - name: Generate Pac-Man SVG
        run: |
          mkdir -p output
          github-contribution-grid-snake --pacman --username PralhadYadawad --output output/pacman.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/pacman.svg
          git commit -m "Updated Pac-Man graph" || echo "No changes to commit"
          git push
