name: Generate and Commit Pac-Man Animation

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight, adjust as needed
  workflow_dispatch: {}  # allows manual trigger

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # allows committing back to the repo

    steps:
      - uses: actions/checkout@v4

      # (Optional) Install tools, convert SVG to GIF if needed
      - name: Convert SVG to GIF
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          convert path/to/your/pacman.svg output/pacman-anim.gif || exit 0

      # OR if you already have the GIF generated in preceding steps, skip this conversion

      - name: Create output directory
        run: mkdir -p output

      - name: Move generated GIF into output/
        run: mv output/pacman-anim.gif output/

      - name: Commit & push generated file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'output/pacman-anim.gif'
          author_name: 'github-actions[bot]'
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          message: 'CI: update Pac-Man animation'
